name: Deployment 

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            docker pull subha250504/flask-app:latest

            docker stop flask-app || true
            docker rm flask-app || true

            docker run -d \
              --name flask-app \
              -p 80:5000 \
              --restart always \
              subha250504/flask-app:latest
