name: Deployment 

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{}}
          username: ${{}}
          key: ${{}}

          script: |
            docker pull subha250504/flask-app:${{ github.sha }}

            docker stop flask-app || true
            docker rm flask-app || true

            docker run -d \
              --name flask-app \
              -p 80:5000 \
              --restart always \
              subha250504/flask-app:${{ github.sha }}
            
            sleep 20

            if curl -f http://localhost; then
              echo "Deployment Successful"
            else
              echo "Deployment Failed"

              docker stop flask-app
              docker rm flask-app   

              docker run -d \
                --name flask-app \
                -p 80:5000 \
                subha250504/flask-app:v1

              exit 1
            fi     